### PR TITLE
Update the read.me

### PR DESCRIPTION
**Pull request by FloydMa1**
did the good doing

### CODE REVIEW

**Review by joppevanbasten — APPROVED** [review]

**Review by MeesMD — APPROVED** [review]
this are very approve I do is the congranturate for the big good

**Review by gwenvis — DISMISSED** [review]
bad

**Review by gwenvis — DISMISSED** [review]
shit

**Review by gwenvis — DISMISSED** [review]
bad again

**Review by gwenvis — APPROVED** [review]
really good!

**Pull request merged**
